// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/model.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resource represents a structured, optional multi-modal input to the model.
//
// This is intentionally minimal and "agnostic": planners can attach references
// (URIs/paths) to externally stored data without changing core planning logic.
type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // e.g., "image", "audio", "file"
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`   // URI or path to the resource (e.g., S3 URL, local temp path)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_proto_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_proto_model_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type PlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Resources     []*Resource            `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"` // Optional multi-modal inputs.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_proto_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_proto_rawDescGZIP(), []int{1}
}

func (x *PlanRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *PlanRequest) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type PlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          string                 `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_proto_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_proto_model_proto_rawDescGZIP(), []int{2}
}

func (x *PlanResponse) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *PlanResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *PlanResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type RAGContextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK           int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	KnowledgeBases []string               `protobuf:"bytes,3,rep,name=knowledge_bases,json=knowledgeBases,proto3" json:"knowledge_bases,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RAGContextRequest) Reset() {
	*x = RAGContextRequest{}
	mi := &file_proto_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGContextRequest) ProtoMessage() {}

func (x *RAGContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGContextRequest.ProtoReflect.Descriptor instead.
func (*RAGContextRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_proto_rawDescGZIP(), []int{3}
}

func (x *RAGContextRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RAGContextRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RAGContextRequest) GetKnowledgeBases() []string {
	if x != nil {
		return x.KnowledgeBases
	}
	return nil
}

type RAGMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Distance      float64                `protobuf:"fixed64,3,opt,name=distance,proto3" json:"distance,omitempty"`
	KnowledgeBase string                 `protobuf:"bytes,4,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGMatch) Reset() {
	*x = RAGMatch{}
	mi := &file_proto_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGMatch) ProtoMessage() {}

func (x *RAGMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGMatch.ProtoReflect.Descriptor instead.
func (*RAGMatch) Descriptor() ([]byte, []int) {
	return file_proto_model_proto_rawDescGZIP(), []int{4}
}

func (x *RAGMatch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RAGMatch) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RAGMatch) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *RAGMatch) GetKnowledgeBase() string {
	if x != nil {
		return x.KnowledgeBase
	}
	return ""
}

func (x *RAGMatch) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type RAGContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*RAGMatch            `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGContextResponse) Reset() {
	*x = RAGContextResponse{}
	mi := &file_proto_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGContextResponse) ProtoMessage() {}

func (x *RAGContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGContextResponse.ProtoReflect.Descriptor instead.
func (*RAGContextResponse) Descriptor() ([]byte, []int) {
	return file_proto_model_proto_rawDescGZIP(), []int{5}
}

func (x *RAGContextResponse) GetMatches() []*RAGMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type ToolRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ToolName string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// JSON string representing the arguments object for the tool.
	ArgsJson string `protobuf:"bytes,2,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	// ---
	// Isolation + resource control contract.
	//
	// These fields are intentionally part of the API *before* we implement a
	// hardened micro-VM runtime (gVisor/Firecracker). The Rust sandbox may ignore
	// them for now, but clients can populate them to future-proof the interface.
	// ---
	ExecutionEnvironment string `protobuf:"bytes,3,opt,name=execution_environment,json=executionEnvironment,proto3" json:"execution_environment,omitempty"` // e.g., "gvisor", "firecracker", "generic-docker"
	CpuLimitMhz          int32  `protobuf:"varint,4,opt,name=cpu_limit_mhz,json=cpuLimitMhz,proto3" json:"cpu_limit_mhz,omitempty"`                         // Max CPU resource limit
	MemoryLimitMb        int32  `protobuf:"varint,5,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"`                   // Max memory allocation
	TimeoutSeconds       int32  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                  // Max runtime before termination
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_proto_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_proto_rawDescGZIP(), []int{6}
}

func (x *ToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolRequest) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

func (x *ToolRequest) GetExecutionEnvironment() string {
	if x != nil {
		return x.ExecutionEnvironment
	}
	return ""
}

func (x *ToolRequest) GetCpuLimitMhz() int32 {
	if x != nil {
		return x.CpuLimitMhz
	}
	return 0
}

func (x *ToolRequest) GetMemoryLimitMb() int32 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

func (x *ToolRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResponse) Reset() {
	*x = ToolResponse{}
	mi := &file_proto_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResponse) ProtoMessage() {}

func (x *ToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResponse.ProtoReflect.Descriptor instead.
func (*ToolResponse) Descriptor() ([]byte, []int) {
	return file_proto_model_proto_rawDescGZIP(), []int{7}
}

func (x *ToolResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ToolResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ToolResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

var File_proto_model_proto protoreflect.FileDescriptor

const file_proto_model_proto_rawDesc = "" +
	"\n" +
	"\x11proto/model.proto\x12\fmodelgateway\"0\n" +
	"\bResource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\"[\n" +
	"\vPlanRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x124\n" +
	"\tresources\x18\x02 \x03(\v2\x16.modelgateway.ResourceR\tresources\"`\n" +
	"\fPlanResponse\x12\x12\n" +
	"\x04plan\x18\x01 \x01(\tR\x04plan\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\"g\n" +
	"\x11RAGContextRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12'\n" +
	"\x0fknowledge_bases\x18\x03 \x03(\tR\x0eknowledgeBases\"\x89\x01\n" +
	"\bRAGMatch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x01R\bdistance\x12%\n" +
	"\x0eknowledge_base\x18\x04 \x01(\tR\rknowledgeBase\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"F\n" +
	"\x12RAGContextResponse\x120\n" +
	"\amatches\x18\x01 \x03(\v2\x16.modelgateway.RAGMatchR\amatches\"\xf1\x01\n" +
	"\vToolRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1b\n" +
	"\targs_json\x18\x02 \x01(\tR\bargsJson\x123\n" +
	"\x15execution_environment\x18\x03 \x01(\tR\x14executionEnvironment\x12\"\n" +
	"\rcpu_limit_mhz\x18\x04 \x01(\x05R\vcpuLimitMhz\x12&\n" +
	"\x0fmemory_limit_mb\x18\x05 \x01(\x05R\rmemoryLimitMb\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\"V\n" +
	"\fToolResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr2\xa4\x01\n" +
	"\fModelGateway\x12@\n" +
	"\aGetPlan\x12\x19.modelgateway.PlanRequest\x1a\x1a.modelgateway.PlanResponse\x12R\n" +
	"\rGetRAGContext\x12\x1f.modelgateway.RAGContextRequest\x1a .modelgateway.RAGContextResponse2S\n" +
	"\vToolService\x12D\n" +
	"\vExecuteTool\x12\x19.modelgateway.ToolRequest\x1a\x1a.modelgateway.ToolResponseB&Z$backend-go-model-gateway/proto;protob\x06proto3"

var (
	file_proto_model_proto_rawDescOnce sync.Once
	file_proto_model_proto_rawDescData []byte
)

func file_proto_model_proto_rawDescGZIP() []byte {
	file_proto_model_proto_rawDescOnce.Do(func() {
		file_proto_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_model_proto_rawDesc), len(file_proto_model_proto_rawDesc)))
	})
	return file_proto_model_proto_rawDescData
}

var file_proto_model_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_model_proto_goTypes = []any{
	(*Resource)(nil),           // 0: modelgateway.Resource
	(*PlanRequest)(nil),        // 1: modelgateway.PlanRequest
	(*PlanResponse)(nil),       // 2: modelgateway.PlanResponse
	(*RAGContextRequest)(nil),  // 3: modelgateway.RAGContextRequest
	(*RAGMatch)(nil),           // 4: modelgateway.RAGMatch
	(*RAGContextResponse)(nil), // 5: modelgateway.RAGContextResponse
	(*ToolRequest)(nil),        // 6: modelgateway.ToolRequest
	(*ToolResponse)(nil),       // 7: modelgateway.ToolResponse
}
var file_proto_model_proto_depIdxs = []int32{
	0, // 0: modelgateway.PlanRequest.resources:type_name -> modelgateway.Resource
	4, // 1: modelgateway.RAGContextResponse.matches:type_name -> modelgateway.RAGMatch
	1, // 2: modelgateway.ModelGateway.GetPlan:input_type -> modelgateway.PlanRequest
	3, // 3: modelgateway.ModelGateway.GetRAGContext:input_type -> modelgateway.RAGContextRequest
	6, // 4: modelgateway.ToolService.ExecuteTool:input_type -> modelgateway.ToolRequest
	2, // 5: modelgateway.ModelGateway.GetPlan:output_type -> modelgateway.PlanResponse
	5, // 6: modelgateway.ModelGateway.GetRAGContext:output_type -> modelgateway.RAGContextResponse
	7, // 7: modelgateway.ToolService.ExecuteTool:output_type -> modelgateway.ToolResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_model_proto_init() }
func file_proto_model_proto_init() {
	if File_proto_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_model_proto_rawDesc), len(file_proto_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_model_proto_goTypes,
		DependencyIndexes: file_proto_model_proto_depIdxs,
		MessageInfos:      file_proto_model_proto_msgTypes,
	}.Build()
	File_proto_model_proto = out.File
	file_proto_model_proto_goTypes = nil
	file_proto_model_proto_depIdxs = nil
}
