# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x0cmodelgateway\"\x1d\n\x0bPlanRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"D\n\x0cPlanResponse\x12\x0c\n\x04plan\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x12\n\nlatency_ms\x18\x03 \x01(\x03\x32P\n\x0cModelGateway\x12@\n\x07GetPlan\x12\x19.modelgateway.PlanRequest\x1a\x1a.modelgateway.PlanResponseB&Z$backend-go-model-gateway/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$backend-go-model-gateway/proto;proto'
  _globals['_PLANREQUEST']._serialized_start=29
  _globals['_PLANREQUEST']._serialized_end=58
  _globals['_PLANRESPONSE']._serialized_start=60
  _globals['_PLANRESPONSE']._serialized_end=128
  _globals['_MODELGATEWAY']._serialized_start=130
  _globals['_MODELGATEWAY']._serialized_end=210
# @@protoc_insertion_point(module_scope)
