import os
import time
import json
import sys
from typing import Any, Dict

import grpc


DEFAULT_GRPC_HOST = "localhost"
DEFAULT_GRPC_PORT = 50051
DEFAULT_GRPC_TIMEOUT_SECONDS = 5.0


def _grpc_target() -> str:
    host = os.environ.get("MODEL_GATEWAY_GRPC_HOST", DEFAULT_GRPC_HOST)
    port_str = os.environ.get("MODEL_GATEWAY_GRPC_PORT", str(DEFAULT_GRPC_PORT))
    try:
        port = int(port_str)
    except ValueError:
        port = DEFAULT_GRPC_PORT
    return f"{host}:{port}"


def generate_stubs() -> None:
    """Best-effort stub generation for bare-metal usage.

    Docker builds generate stubs in [`backend-python-agent/Dockerfile`](backend-python-agent/Dockerfile:1).
    This helper exists so local dev can run:
      `python -c "from grpc_client import generate_stubs; generate_stubs()"`
    """

    try:
        from grpc_tools import protoc  # type: ignore
    except Exception as e:  # pragma: no cover
        raise RuntimeError(
            "grpcio-tools is not installed. Install requirements and retry."
        ) from e

    proto_dir = os.path.join(os.path.dirname(__file__), "proto")
    proto_path = os.path.join(proto_dir, "model.proto")
    if not os.path.exists(proto_path):
        raise FileNotFoundError(proto_path)

    # protoc.main expects argv-like list (first entry ignored).
    result = protoc.main(
        [
            "protoc",
            f"-I{proto_dir}",
            f"--python_out={proto_dir}",
            f"--grpc_python_out={proto_dir}",
            proto_path,
        ]
    )
    if result != 0:
        raise RuntimeError(f"protoc failed with exit code {result}")


def _import_stubs():
    try:
        # Generated by grpc_tools.protoc. The generated *_grpc.py commonly uses
        # `import model_pb2` (top-level), so ensure the proto directory is on sys.path.
        proto_dir = os.path.join(os.path.dirname(__file__), "proto")
        if proto_dir not in sys.path:
            sys.path.insert(0, proto_dir)

        import model_pb2  # type: ignore
        import model_pb2_grpc  # type: ignore

        return model_pb2, model_pb2_grpc
    except Exception as e:
        raise RuntimeError(
            "Python gRPC stubs are missing. Run generate_stubs() (bare metal) or rebuild the container."
        ) from e


async def get_llm_plan(prompt: str) -> Dict[str, Any]:
    """Call the Go Model Gateway via gRPC and return a JSON-serializable payload."""

    model_pb2, model_pb2_grpc = _import_stubs()
    target = _grpc_target()

    timeout = float(os.environ.get("MODEL_GATEWAY_GRPC_TIMEOUT_SECONDS", DEFAULT_GRPC_TIMEOUT_SECONDS))
    start = time.time()

    async with grpc.aio.insecure_channel(target) as channel:
        stub = model_pb2_grpc.ModelGatewayStub(channel)
        resp = await stub.GetPlan(model_pb2.PlanRequest(prompt=prompt), timeout=timeout)

    elapsed_ms = int((time.time() - start) * 1000)

    # Optional: if the gateway encodes structured data into `plan`, decode it.
    model_type = resp.model_name
    steps = None
    try:
        decoded = json.loads(resp.plan)
        if isinstance(decoded, dict):
            model_type = decoded.get("model_type", model_type)
            steps = decoded.get("steps")
        elif isinstance(decoded, list):
            steps = decoded
    except Exception:
        pass

    payload: Dict[str, Any] = {
        "target": target,
        "grpc_latency_ms": elapsed_ms,
        "plan": resp.plan,
        "model_name": resp.model_name,
        "latency_ms": resp.latency_ms,
        "model_type": model_type,
    }
    if steps is not None:
        payload["steps"] = steps
    return payload

