// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: proto/model.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelGateway_GetPlan_FullMethodName = "/modelgateway.ModelGateway/GetPlan"
)

// ModelGatewayClient is the client API for ModelGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelGatewayClient interface {
	GetPlan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
}

type modelGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewModelGatewayClient(cc grpc.ClientConnInterface) ModelGatewayClient {
	return &modelGatewayClient{cc}
}

func (c *modelGatewayClient) GetPlan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	out := new(PlanResponse)
	err := c.cc.Invoke(ctx, ModelGateway_GetPlan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelGatewayServer is the server API for ModelGateway service.
// All implementations must embed UnimplementedModelGatewayServer
// for forward compatibility.
type ModelGatewayServer interface {
	GetPlan(context.Context, *PlanRequest) (*PlanResponse, error)
	mustEmbedUnimplementedModelGatewayServer()
}

// UnimplementedModelGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedModelGatewayServer struct{}

func (UnimplementedModelGatewayServer) GetPlan(context.Context, *PlanRequest) (*PlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlan not implemented")
}
func (UnimplementedModelGatewayServer) mustEmbedUnimplementedModelGatewayServer() {}

// UnsafeModelGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelGatewayServer will
// result in compilation errors.
type UnsafeModelGatewayServer interface {
	mustEmbedUnimplementedModelGatewayServer()
}

func RegisterModelGatewayServer(s grpc.ServiceRegistrar, srv ModelGatewayServer) {
	s.RegisterService(&ModelGateway_ServiceDesc, srv)
}

func _ModelGateway_GetPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelGatewayServer).GetPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelGateway_GetPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelGatewayServer).GetPlan(ctx, req.(*PlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelGateway_ServiceDesc is the grpc.ServiceDesc for ModelGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "modelgateway.ModelGateway",
	HandlerType: (*ModelGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlan",
			Handler:    _ModelGateway_GetPlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/model.proto",
}
